### ISSUE TITLE
`IndexError: list index out of range `

### ISSUE THREAD

**Issue by AndreaGuarracino** [fedorrik/stv#1]
With

```
 ./stv.sh AS-HOR+SF-vs-haplotype1-0000002.fa.bed
```

I get

```
Traceback (most recent call last):                                                                                                                                      │(base) ➜  stv git:(main) ✗ nano scripts/mon2stv.py                                                                                                                   
  File "/lizardfs/guarracino/git/stv/scripts/coloring.py", line 81, in <module>                                                                                         │(base) ➜  stv git:(main) ✗ python3 scripts/mon2stv.py AS_liveHORs.bed | less -S
    for stv in stv_clever_coloring(current_bed, stv_stat):                                                                                                              │Traceback (most recent call last):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                               │  File "/lizardfs/guarracino/git/stv/scripts/mon2stv.py", line 242, in <module>
  File "/lizardfs/guarracino/git/stv/scripts/coloring.py", line 23, in stv_clever_coloring                                                                              │    print("2 strand:", strand_prev);
    line[8] = colors[name]                                                                                                                                              │BrokenPipeError: [Errno 32] Broken pipe
    ~~~~^^^                                                                                                                                                             │(base) ➜  stv git:(main) ✗ python3 scripts/mon2stv.py AS_liveHORs.bed | less -S
IndexError: list assignment index out of range
```

This happens because the first row of `stv_raw.bed` has an empty strand field:

```
head stv_raw.bed -n 2
haplotype1-0000002      1894525 1894696 S2C18H1L.12     0               1894525 1894696 0,0,0
haplotype1-0000002      1894696 1895541 S2C18H1L.1-3_8-9        0       +       1894696 1895541 0,0,0
```   
[AS-HOR+SF-vs-haplotype1-0000002.fa.bed.gz](https://github.com/fedorrik/stv/files/13207415/AS-HOR%2BSF-vs-haplotype1-0000002.fa.bed.gz)

**Comment by fedorrik** [comment]
This bug appeared after the previous commit. Fixed it. Thanks for finding it

**Comment by AndreaGuarracino** [comment]
Cheers!
